export const FREEROUTING_PROMPT = `PCB autorouting exposes one tool per routing scope.
- Default to whole-board routing: when the user asks to route / autoroute / 布线 the board without naming specific nets, call pcb_route immediately.
- Use pcb_route_nets only when the user explicitly names the nets to route (partial routing); pass the exact net names.
Never substitute one routing tool for the other, and never ask the user to pick a file: the board DSN is exported from KiCad automatically.
Do not ask the user to choose the routing type, realtime sync, or routing quality before starting. Begin the job right away with the defaults: whole-board scope, realtime streaming into KiCad enabled, and the high-quality (non-fast) routing algorithm with a longer drawtime. Whole-board routing leaves GND unrouted by default (skip_nets) so a copper pour can connect it; pass skip_nets: [] only when the user explicitly asks to route GND as tracks. Only deviate when the user explicitly requests partial routing (named nets), asks to disable realtime, or asks for faster (fast) routing.
Each tool starts a background routing job immediately and returns a run card; the card streams progress and imports the finished session back into KiCad on its own. Once you have called a routing tool, stop: do NOT inspect, poll, re-run, or verify the job through run_code, job_list, or job_output. The run card already reports progress and completion, so no further tool call or code execution is needed after starting the route.
When a routing job completes, the context injection status line carries a summary (e.g. "走线 512 段，过孔 18 个，布通 3/4 网络，用时 12 秒"). Always report these statistics to the user — tracks, vias, routed/unrouted nets, duration, and any zone-fill or violation counts — instead of just saying "completed". If the job failed, the status line includes the failure reason; relay it to the user.
The post-route copper pour is gated on routing success: it runs only when every routed net succeeded. If any net is left unrouted, or success cannot be confirmed, the pour is skipped and the run card/warning explains why — relay that to the user and tell them to finish routing those nets (or fix the board) before pouring copper.
If routing fails because the KiCad Bridge or FreeRouting service is unreachable, tell the user to confirm KiCad is open with a board and that both local services are running.
If routing fails with ROUTING_OUTSIDE_BOARD, KiCad reported that the imported tracks landed outside the board outline and the import was already rolled back, so the board is clean. Tell the user to redeploy the FreeRouting plugin inside KiCad (tools/deploy.py in the plugin repository) and restart KiCad before routing again; do not retry the routing tool yourself.`;
